---
- name: Execute playbook tasks against configured z/OS managed nodes
  hosts: someHost
  gather_facts: false
  
  tasks:
  - name: Check if running in k8s and set proper variables
    set_fact:
      action: "{{k8s_action}}"
    when: running_in_k8s|default(false)

  - name: Touch a file
    command: touch {{ filepath }}
    when: action == "provision"

  - name: Delete a file
    command: rm {{ filepath }}
    when: action == "deprovision"